# Generated by Django 3.1.4 on 2024-03-22 07:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Название категории не соответствует, можно использовать только буквы, цифры и нижнее подчеркивания.', regex='^[\\w.@+-]+$')], verbose_name='Название категории')),
                ('text', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Описание категории не соответствует, можно использовать только буквы, цифры и нижнее подчеркивания.', regex='^[\\w.@+-]+$')], verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Название сервиса не соответствует, можно использовать только буквы, цифры и нижнее подчеркивания.', regex='^[\\w.@+-]+$')], verbose_name='Название сервиса')),
                ('image', models.ImageField(blank=True, upload_to='services/', verbose_name='Логотип сервиса')),
                ('text', models.TextField(verbose_name='Описание сервиса')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Название условия подписки не соответствует, можно использовать только буквы, цифры и нижнее подчеркивания.', regex='^[\\w.@+-]+$')])),
                ('duration', models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Название условия подписки не соответствует, можно использовать только буквы, цифры и нижнее подчеркивания.', regex='^[\\w.@+-]+$')])),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('cashback', models.PositiveIntegerField(verbose_name='Кэшбэк')),
            ],
            options={
                'verbose_name': 'Условия подписки',
                'verbose_name_plural': 'Условия подписок',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TermsInService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_recipe', to='services.service', verbose_name='Ингредиент')),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_list', to='services.terms', verbose_name='Рецепт')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='services.service', verbose_name='Сервис')),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='services.terms', verbose_name='Условия')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ('id',),
            },
        ),
    ]
