# Generated by Django 3.1.4 on 2024-03-22 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20240322_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='cashback',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Название условия подписки не соответствует, можно использовать только буквы, цифры и нижнее подчеркивания.', regex='^[\\w.@+-]+$')], verbose_name='Кэшбэк'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
    ]
