# Generated by Django 4.1.2 on 2024-03-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "services",
            "0002_alter_bankcard_id_alter_category_id_alter_service_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="terms",
            name="duration",
            field=models.CharField(
                choices=[
                    ("one_month", "Один месяц"),
                    ("three_months", "Три месяца"),
                    ("six_months", "Шесть месяцев"),
                    ("one_year", "Один год"),
                ],
                max_length=150,
                verbose_name="Продолжительность",
            ),
        ),
    ]
