# Generated by Django 4.1.2 on 2024-03-26 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(blank=True, verbose_name='Дата окончания подписки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата начала подписки'),
        ),
    ]
