# Generated by Django 4.1.2 on 2024-03-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_alter_terms_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terms",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
