# Generated by Django 4.1.2 on 2024-03-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Выгодное предложение'),
        ),
    ]
