# Generated by Django 4.1.2 on 2024-03-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0004_alter_terms_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankcard",
            name="balance",
            field=models.PositiveIntegerField(default=5000, verbose_name="Баланс"),
        ),
    ]
