# Generated by Django 4.1.2 on 2024-03-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_terms_is_featured'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
    ]
