# Generated by Django 4.1.2 on 2024-03-27 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0005_alter_subscription_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankcard',
            options={'ordering': ('id',), 'verbose_name': 'Банковская карта', 'verbose_name_plural': 'Банковские карты'},
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sercvice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_comparison', to=settings.AUTH_USER_MODEL, verbose_name='сервис')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comparison', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Сравнение',
                'verbose_name_plural': 'Сравнении',
                'ordering': ('id',),
            },
        ),
    ]
