# Generated by Django 3.1.4 on 2024-03-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20240322_2007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryInService',
        ),
    ]
