# Generated by Django 4.1.2 on 2024-03-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_bankcard_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="terms",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("free", "Бесплатная подписка"),
                    ("paid", "Платная подписка"),
                    ("trial", "Пробная подписка"),
                ],
                default="free",
                max_length=100,
                verbose_name="Тип подписки",
            ),
        ),
    ]
