# Generated by Django 4.1.2 on 2024-03-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0006_terms_subscription_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Лучшее предложение"),
        ),
    ]
