# Generated by Django 3.1.4 on 2024-03-23 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0006_delete_categoryinservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='terms',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='servece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='services.service', verbose_name='Сервис'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
    ]
