# Generated by Django 4.1.2 on 2024-03-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_bankcard_options_comparison'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparison',
            old_name='sercvice',
            new_name='service',
        ),
    ]
