# Generated by Django 4.1.2 on 2024-03-27 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_rename_sercvice_comparison_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_comparison', to='services.service', verbose_name='сервис'),
        ),
    ]
