# Generated by Django 4.1.2 on 2024-03-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0007_service_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankcard",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активная карта"),
        ),
    ]
