# Generated by Django 3.1.4 on 2024-03-21 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.PositiveIntegerField(default=10000, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Имейл'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=150, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Телефонный номер должен быть формата: +"999999999".', regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Имя пользователя не соответствует, можно использовать только буквы, цифры и нижнее подчеркивания.', regex='^[\\w.@+-]+$')], verbose_name='Имя пользователя'),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
