# Generated by Django 3.1.4 on 2024-03-23 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240323_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Телефонный номер должен быть формата: +"999999999".', regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефонный номер'),
        ),
    ]
