# Generated by Django 4.1.2 on 2024-03-23 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_email_alter_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="balance",
        ),
    ]
